Name:           ros-jade-hector-components-description
Version:        0.4.1
Release:        0%{?dist}
Summary:        ROS hector_components_description package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/hector_components_description
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-hector-sensors-description
Requires:       ros-jade-hector-xacro-tools
Requires:       ros-jade-xacro
BuildRequires:  ros-jade-catkin

%description
hector_components_description contains URDF xacro macros for robot components,
so they are easily attachable to robot models.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Sun Nov 08 2015 Stefan Kohlbrecher <kohlbrecher@sim.tu-darmstadt.de> - 0.4.1-0
- Autogenerated by Bloom

* Sat Nov 07 2015 Stefan Kohlbrecher <kohlbrecher@sim.tu-darmstadt.de> - 0.4.0-0
- Autogenerated by Bloom

