Name:           ros-indigo-hector-components-description
Version:        0.3.2
Release:        0%{?dist}
Summary:        ROS hector_components_description package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/hector_components_description
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-hector-sensors-description
Requires:       ros-indigo-hector-xacro-tools
Requires:       ros-indigo-xacro
BuildRequires:  ros-indigo-catkin

%description
hector_components_description contains URDF xacro macros for robot components,
so they are easily attachable to robot models.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Sep 01 2014 Stefan Kohlbrecher <kohlbrecher@sim.tu-darmstadt.de> - 0.3.2-0
- Autogenerated by Bloom

